# Generated by Django 5.1.7 on 2026-09-28 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consentbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consent",
            name="dependent_user",
        ),
        migrations.AddField(
            model_name="consent",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Legal guardian who authorized consent on behalf of the user (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guardian_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentscript",
            name="study_info",
            field=models.URLField(
                default="https://gregorconsortium.org/learning", max_length=2048
            ),
        ),
        migrations.AddField(
            model_name="consentsession",
            name="consent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="consentbot.consent",
            ),
        ),
        migrations.AddField(
            model_name="consentsession",
            name="dependants_consented",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="child_full_name_consent",
            field=models.CharField(
                blank=True,
                help_text="Name of the dependent child if applicable.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_age_group",
            field=models.CharField(
                choices=[
                    ("<=6", "<=6"),
                    ("7-17", "7-17"),
                    (">=18", ">=18"),
                    (">=18 guardianship", ">=18 guardianship"),
                ],
                help_text="Age group classification at the time of consent (e.g., '<=6', '7-17', '>=18').",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_script",
            field=models.ForeignKey(
                blank=True,
                help_text="Consent script (chat flow) associated with this consent instance.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_consents",
                to="consentbot.consentscript",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_statements",
            field=models.TextField(
                default="",
                help_text="Full textual content of the consent statements acknowledged.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consented_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the consent was given.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Auto-generated timestamp of when this record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="return_actionable_secondary_results",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user consents to receive actionable secondary results.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="return_primary_results",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user consents to receive primary results.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="return_secondary_results",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user consents to receive non-actionable secondary results.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="store_phi_other_studies",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user consents to store PHI for future unrelated studies.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="store_phi_this_study",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user consents to store PHI for the current study.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="store_sample_other_studies",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user consents to store samples for future unrelated studies.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="store_sample_this_study",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user consents to store samples for the current study.",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="user",
            field=models.ForeignKey(
                help_text="The individual for whom the consent applies (adult or dependent child).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="user_consent_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Primary key identifier for the consent record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="user_full_name_consent",
            field=models.CharField(
                default="",
                help_text="Name of the user (or guardian) who signed the consent form.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="consentchatturn",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_turns",
                to="consentbot.consentsession",
            ),
        ),
    ]
